name: Forge of Creation

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    
       - name: Cleaning Disks
         uses: rokibhasansagar/slimhub_actions@v3

       - name: Checkingout Forge of Creation
         uses: actions/checkout@main
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Canceling duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Initializing Server
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning repository
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@${{ secrets.BOT_REPO }} alienx
       - name: Running Forge of Creation
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd alienx
           docker build . -t alienx
           docker run alienx
       - name: Loop Forge of Creation
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "alienx : $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GIT_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
